const BOARD_SIZE_PIXELS = 700;
const SQUARE_SIZE_PIXELS = BOARD_SIZE_PIXELS / 8;
const PIECE_SIZE_PIXELS = SQUARE_SIZE_PIXELS * 0.8;
const WHITE_SQUARE_BACKGROUND = "#eeeed2";
const BLACK_SQUARE_BACKGROUND = "#769656";

const LAYER_SQUARE_STATE = 10;
const LAYER_PIECE = 20;
const LAYER_MOVE_INDICATOR = 30;
const LAYER_GHOST_PIECE = 40;
const LAYER_QUEENING_MENU_OVERLAY = 50;
const LAYER_QUEENING_MENU = 60;

export {
  BOARD_SIZE_PIXELS,
  SQUARE_SIZE_PIXELS,
  PIECE_SIZE_PIXELS,
  WHITE_SQUARE_BACKGROUND,
  BLACK_SQUARE_BACKGROUND,
  LAYER_GHOST_PIECE,
  LAYER_MOVE_INDICATOR,
  LAYER_PIECE,
  LAYER_SQUARE_STATE,
  LAYER_QUEENING_MENU,
  LAYER_QUEENING_MENU_OVERLAY,
};
